all: gimme called lazy slot push

gimme:
	mksong -o -d example_output/ gimme_a_u.cho.txt 

called:
	mksong -o -d example_output/ 	i_called_your_name.cho.txt

lazy:
	mksong  -d example_output/  -b sample-lazy.book.txt

slot:
	mksong -o -d example_output/ slot_machine_baby.cho.txt

push:
	git commit -a -m "Updated examples"
	git push